[workspace]
members = ["kineplex-core", "kineplex-net", "kineplex-node"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "AGPL-3.0-only"
authors = ["Gemirson dos Santos Silva & Engineering Team"]
repository = "https://github.com/gemirson/kineplex"

[workspace.dependencies]
bytes = "=1.5.0"
foca = { version = "=0.10.0", features = ["postcard-codec", "std", "tracing"] }
rand = "=0.8.5"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
time = "=0.3.36"
tokio = { version = "=1.35.1", features = ["macros", "net", "rt", "signal", "sync", "time"] }
tracing = "=0.1.41"
tracing-appender = { version = "=0.2.3", default-features = false }
tracing-subscriber = { version = "=0.3.19", default-features = false, features = ["env-filter", "fmt", "json"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
print_stderr = "deny"
print_stdout = "deny"
