[package]
name = "kineplex-net"
description = "Network address primitives for KinePlex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
dashmap.workspace = true
flatbuffers.workspace = true
foca.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
parking_lot.workspace = true
anyhow.workspace = true
thiserror.workspace = true
async-trait.workspace = true
kineplex-core = { path = "../kineplex-core" }

[build-dependencies]
flatc-rust.workspace = true

[lints]
workspace = true
