[package]
name = "kineplex-net"
description = "Network address primitives for KinePlex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
dashmap.workspace = true
flatbuffers.workspace = true
foca.workspace = true
rand.workspace = true
serde.workspace = true
sysinfo.workspace = true
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
flatc-rust.workspace = true

[lints]
workspace = true
