//! Idiomatic user APIs for building KinePlex Wasm synapses and Arrow jobs.

extern crate self as kineplex_sdk;

pub use kineplex_sdk_macros::synapse;

pub mod arrow;
pub mod graph;

pub mod prelude {
    pub use crate::arrow::{KineColumnExt, KineRecordBatchBuilder};
    pub use crate::graph::{KineGraph, NativeOperator};
    pub use crate::synapse;
    pub use arrow::array::RecordBatch;
}

/// Attribute path matching the documented `#[kineplex::synapse]` syntax.
pub mod kineplex {
    pub use kineplex_sdk_macros::synapse;
}

pub mod __private {
    use std::alloc::{alloc, dealloc, Layout};
    use std::io::Cursor;
    use std::sync::atomic::{AtomicI32, Ordering};

    use arrow::array::RecordBatch;
    use arrow::ipc::reader::StreamReader;
    use arrow::ipc::writer::StreamWriter;

    const MAX_IPC_BYTES: usize = 2 * 1024 * 1024 * 1024;
    static RESULT_SIZE: AtomicI32 = AtomicI32::new(0);

    /// Allocates guest-owned ABI memory. Generated by the SDK macro for Wasm.
    pub fn allocate(size: i32) -> i32 {
        let Ok(size) = usize::try_from(size) else {
            return 0;
        };
        if size == 0 || size > MAX_IPC_BYTES {
            return 0;
        }
        let Ok(layout) = Layout::from_size_align(size, 8) else {
            return 0;
        };
        // SAFETY: `layout` is non-zero and valid; the matching deallocator is exported.
        unsafe { alloc(layout) as usize as i32 }
    }

    /// Releases a pointer previously allocated through `alloc_ffi`.
    pub fn deallocate(pointer: i32, size: i32) {
        let (Ok(pointer), Ok(size)) = (usize::try_from(pointer), usize::try_from(size)) else {
            return;
        };
        if pointer == 0 || size == 0 || size > MAX_IPC_BYTES {
            return;
        }
        let Ok(layout) = Layout::from_size_align(size, 8) else {
            return;
        };
        // SAFETY: the ABI requires this pointer and size to come from alloc_ffi.
        unsafe {
            dealloc(pointer as *mut u8, layout);
        }
    }

    /// Decodes the input IPC stream described by the FT-028 version/length block.
    pub fn decode_input(input_ptr: i32, descriptor_ptr: i32) -> Result<RecordBatch, String> {
        let pointer = usize::try_from(input_ptr).map_err(|_| "negative Arrow input pointer")?;
        let descriptor =
            usize::try_from(descriptor_ptr).map_err(|_| "negative schema descriptor pointer")?;
        if pointer == 0 || descriptor == 0 {
            return Err("null Arrow IPC pointer".to_owned());
        }
        // SAFETY: the host passes this descriptor in guest linear memory and supplies 8 bytes.
        let descriptor = unsafe { std::slice::from_raw_parts(descriptor as *const u8, 8) };
        let version = u32::from_le_bytes(
            descriptor[..4]
                .try_into()
                .map_err(|_| "invalid descriptor")?,
        );
        let length = u32::from_le_bytes(
            descriptor[4..]
                .try_into()
                .map_err(|_| "invalid descriptor")?,
        ) as usize;
        if version != 1 || length == 0 || length > MAX_IPC_BYTES {
            return Err("invalid Arrow IPC descriptor".to_owned());
        }
        // SAFETY: input_ptr and its length are guest-owned and were allocated by the host ABI.
        let bytes = unsafe { std::slice::from_raw_parts(pointer as *const u8, length) };
        let mut reader =
            StreamReader::try_new(Cursor::new(bytes), None).map_err(|error| error.to_string())?;
        let batch = reader
            .next()
            .transpose()
            .map_err(|error| error.to_string())?
            .ok_or_else(|| "input stream contained no batch".to_owned())?;
        if reader.next().is_some() {
            return Err("input stream must contain one batch".to_owned());
        }
        Ok(batch)
    }

    /// Encodes one result batch into separately allocated guest memory.
    pub fn encode_output(batch: &RecordBatch) -> Result<i32, String> {
        let mut bytes = Vec::new();
        {
            let mut writer = StreamWriter::try_new(&mut bytes, batch.schema().as_ref())
                .map_err(|error| error.to_string())?;
            writer.write(batch).map_err(|error| error.to_string())?;
            writer.finish().map_err(|error| error.to_string())?;
        }
        if bytes.is_empty() || bytes.len() > MAX_IPC_BYTES || bytes.len() > i32::MAX as usize {
            return Err("Arrow IPC result exceeds the ABI limit".to_owned());
        }
        let pointer = allocate(bytes.len() as i32);
        if pointer == 0 {
            return Err("unable to allocate Arrow IPC result".to_owned());
        }
        // SAFETY: allocation returned at least `bytes.len()` writable bytes.
        unsafe {
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), pointer as usize as *mut u8, bytes.len());
        }
        RESULT_SIZE.store(bytes.len() as i32, Ordering::Release);
        Ok(pointer)
    }

    /// Result size returned by the preceding generated entry point.
    pub fn result_size() -> i32 {
        RESULT_SIZE.load(Ordering::Acquire)
    }

    /// Marks a caught panic or ABI failure for the host.
    pub fn set_result_error() {
        RESULT_SIZE.store(-1, Ordering::Release);
    }
}

#[cfg(test)]
mod macro_expansion {
    use arrow::array::RecordBatch;

    #[crate::synapse]
    fn passthrough(batch: RecordBatch) -> RecordBatch {
        batch
    }

    #[test]
    fn generated_guest_exports_are_linked() {
        let _entry: extern "C" fn(i32, i32) -> i32 = kineplex_run;
        let _allocator: extern "C" fn(i32) -> i32 = alloc_ffi;
        let _size: extern "C" fn() -> i32 = kineplex_result_size;
        let _user_fn: fn(RecordBatch) -> RecordBatch = passthrough;
    }
}
